raw_assets_dir: assets/images
encrypted_assets_dir: assets/encrypted
map_output: lib/generated/asset_shield_map.dart
compression: zstd
compression_level: 3
extensions:
  - .png
  - .jpg
  - .jpeg
  - .json
  - .mp3
key: "qQ1FTjt5DqqMCK2Jl7VtyIn1z0MxlfG4iA+amyvTO6I="
emit_key: true
